#!/usr/bin/env bash
if [[ -n "$DEBUG" ]]; then 
  set -x
fi

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895


cd ~/branches/production/extent_stats
./calisphere_arks.py ~/servers/front/conf/

cd $DIR
./DCme

~/servers/front/conf/generate_maps.bash

~/servers/front/bin/apachectl graceful
